CXX := g++
CSSFLAGS := -std=c++17 -02 -Wall -Wextra -I../../shared

all: test-simulator

test-simulator: main.cpp
    $(CXX) $(CSSFLAGS) $^ -O $@

test: test-simulator
    ./test-simulator

clean:
    rm -f test-simulator

