name: Build firmware

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [esp32:dev, nodemcu-32s]
        project: [controller, scoreboard]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Cache PIO + pip to speed up builds
      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-pio-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install --upgrade platformio cpplint

      - name: Lint shared headers
        run: |
          echo "Running cpplint on shared code..."
          cpplint --recursive --quiet shared || true


      - name: Build Firmware (${{ matrix.project }} - ${{ matrix.board }})
        run: |
          pio run -d ${{ matrix.project }} -e ${{ matrix.board }}
  
