name: Firmware Unit Tests

on:
  push:
    paths:
      - "shared/**"
      - "tools/**"
      - ".github/workflows/test.yml"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Simulation Tests
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          cd tools/test-simulator
          make test

